### ISSUE TITLE
Validation through different port

### ISSUE THREAD

**Issue by roshanjonah** [reacherhq/check-if-email-exists#877]
As you know, many times port 25 is blocked by hosting providers for obvious reasons but with our SOCKS5, we can use port 587/465, I was wondering if it was possible to use port 587/465 for validating emails as opposed to port 25. If not, how easy is it to implement? Thank you! RJ

**Comment by amaurym** [comment]
Tha's a good idea! I think it's pretty easy to implement, you just need to add another field `port` on CheckEmailInput.

would you like to create a PR?

**Comment by amaurym** [comment]
This issue could be done in the following steps:

1. Add a `port: u16` field to [CheckEmailInput](https://github.com/reacherhq/check-if-email-exists/blob/291412338e1bc53937ed4a4c0f4e6c5ffe8cca68/core/src/util/input_output.rs#L37), add its default to 25.
2. Add a `pub fn port()` to it as a setter in the builder pattern.
3. For `check_smtp`, instead of calling with port `SMTP_PORT` (the default), we should call with `input.port` [here](https://github.com/reacherhq/check-if-email-exists/blob/291412338e1bc53937ed4a4c0f4e6c5ffe8cca68/core/src/lib.rs#L173).
